source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'SnapKit'
pod 'SDWebImage', '~> 3.7.5'
pod 'IQKeyboardManagerSwift', '~> 4.0.1'
pod 'MGSwipeTableCell', '~> 1.5.5'
use_frameworks!
pod 'MJRefresh'
